### ISSUE TITLE
Where to config PHP settings

### ISSUE THREAD

**Issue by vyskoczilova** [10up/wp-local-docker-docs#22]
**Describe your question**

Hi, where could I find a php.ini file or another config? I need a bigger timeout & memory for proceeding with some plugins. I've looked into docs, but I haven't found anything in there. (I'm new to docker though).

Thanks in advance

**Comment by dustinrue** [comment]
For any project you create you'll find `config/php-fpm/docker-php-ext-xdebug.ini` in the project directory. You can override PHP settings in that file.

**Comment by vyskoczilova** [comment]
Ah, so easy :) Thanks a lot!

**Comment by frankypixels** [comment]
Hi, not so easy. 

I've added:
`
max_execution_time = 360
upload_max_filesize = 256M
post_max_size= 256M
`
And it's not registering in phpmyadmin. Is there documentation on this somewhere?
