### ISSUE TITLE
2.8.0 broken. Can't install WP.

### ISSUE THREAD

**Issue by joseffb-mla** [10up/wp-local-docker-docs#32]
**Describe the bug**
Can't install WP with create option

**Steps to Reproduce**
I run create, then add alias, https, proxy to live site, choose php 7.1, and tell it to install a subsite WP multi site.

**Expected behavior**
run install to success

**Screenshots**
```
Downloading WordPress
Downloading WordPress 5.6 (en_US)...
md5 hash verified: cfc30949a5cd2d3b52151cb78bfa1a70
...  (same with every WP file as below)
PHP Warning:  copy(/var/www/html//wp-comments-post.php): failed to open stream: No such file or directory in phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Extractor.php on line 195
Success: WordPress downloaded.
Configuring WordPress
Error: This does not seem to be a WordPress installation.
Pass --path=`path/to/wordpress` or run `wp core download`.
node:child_process:636
    err = new Error(msg);
          ^

Error: Command failed: docker-compose exec phpfpm wp config create --force --dbname=mla-test --dbuser=wordpress --dbpass=password --dbhost=mysql
    at checkExecSyncError (node:child_process:636:11)
    at execSync (node:child_process:672:15)
    at Object.configure (/usr/local/lib/node_modules/wp-local-docker/src/wordpress.js:26:5)
    at async createEnv (/usr/local/lib/node_modules/wp-local-docker/src/create.js:420:9)
    at async Object.command (/usr/local/lib/node_modules/wp-local-docker/src/create.js:471:13)
    at async init (/usr/local/lib/node_modules/wp-local-docker/index.js:67:13) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 15687,
  stdout: null,
  stderr: null
}
```

**Environment information**
 - Device: iMac 2019
 - OS: MacOs Big Sur v11.1
 
**Additional context**
It looks like the link between my local /wp-loc al-docker-sites/site/wordpress folder and /var/www/html on the container isn't linking.

**Comment by jeffpaul** [comment]
@joseffb-mla note that v2.8.1 was recently released, can you please try again with that version to see if your issue still exists?

**Comment by joseffb-mla** [comment]
I ran it yesterday with a standard site config and it worked. I will need to run it as a multi site today and see if it fails (which I doubt it will)

**Comment by jeffpaul** [comment]
@joseffb-mla can you confirm if this is working for you on multisite?

**Comment by leobaiano** [comment]
I am using version 2.8.1 and experiencing the exact same error on a single site installation, does anyone have any ideas?

I use macbook.
